# Generated by Django 5.0.6 on 2024-11-16 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioTitleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorytitle', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MusicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musicName', models.CharField(max_length=150)),
                ('musicImage', models.ImageField(blank=True, upload_to='uploads')),
                ('status', models.BooleanField(default=False, help_text='0-show,1-Hidden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoName', models.CharField(max_length=150)),
                ('videoImage', models.ImageField(upload_to='uploads/videos')),
                ('bgvideo', models.FileField(upload_to='uploads/videos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artistName', models.CharField(max_length=150)),
                ('artistImage', models.ImageField(upload_to='uploads')),
                ('artistDescription', models.CharField(max_length=1500)),
                ('status', models.BooleanField(default=False, help_text='show-0,Hidden=1')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('musicModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='starApp.audiotitlemodel')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cltnImage', models.ImageField(upload_to='uploads')),
                ('audio', models.FileField(upload_to='audios')),
                ('songname', models.CharField(max_length=150)),
                ('movie', models.CharField(max_length=150)),
                ('artist', models.CharField(max_length=150)),
                ('duration', models.FloatField()),
                ('favourite', models.BooleanField(default=False, help_text='show-0,Trending-1')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categoryModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='starApp.categorymodel')),
            ],
        ),
        migrations.AddField(
            model_name='audiotitlemodel',
            name='musickey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='starApp.musicmodel'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfBirth', models.DateField(null=True)),
                ('profilePicture', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoTitleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorytitle', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('videomodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='starApp.videosmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=150)),
                ('videodescription', models.CharField(max_length=1500)),
                ('videothumbnail', models.ImageField(upload_to='uploads/videos')),
                ('video', models.FileField(upload_to='uploads/videos')),
                ('like', models.BooleanField(default=False, help_text='default-0,like-1')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('videotitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='starApp.videotitlemodel')),
            ],
        ),
    ]
