# Generated by Django 5.0.6 on 2025-12-12 18:30

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioTitleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorytitle', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'starapp_audiotitlemodel',
            },
        ),
        migrations.CreateModel(
            name='carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('alt_text', models.CharField(default='slide_image', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'starapp_carousel',
            },
        ),
        migrations.CreateModel(
            name='MusicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musicName', models.CharField(max_length=150)),
                ('musicImage', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('status', models.BooleanField(default=False, help_text='0-show,1-Hidden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'starapp_musicmodel',
            },
        ),
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('thumb_text', models.CharField(default='slide_image', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'starapp_thumbnail',
            },
        ),
        migrations.CreateModel(
            name='VideosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoName', models.CharField(max_length=150)),
                ('videoImage', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('bgvideo', cloudinary.models.CloudinaryField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'starapp_videosmodel',
            },
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artistName', models.CharField(max_length=150)),
                ('artistImage', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('artistDescription', models.CharField(max_length=1500)),
                ('status', models.BooleanField(default=False, help_text='show-0,Hidden=1')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('musicModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='starApp.audiotitlemodel')),
            ],
            options={
                'db_table': 'starapp_categorymodel',
            },
        ),
        migrations.CreateModel(
            name='CollectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cltnImage', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('audio', models.URLField(blank=True, max_length=500, null=True)),
                ('songname', models.CharField(max_length=150)),
                ('movie', models.CharField(max_length=150)),
                ('artist', models.CharField(max_length=150)),
                ('duration', models.FloatField()),
                ('favourite', models.BooleanField(default=False, help_text='show-0,Trending-1')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categoryModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='starApp.categorymodel')),
            ],
            options={
                'db_table': 'starapp_collectionmodel',
            },
        ),
        migrations.AddField(
            model_name='audiotitlemodel',
            name='musickey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='starApp.musicmodel'),
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'starapp_otpverification',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfBirth', models.DateField(null=True)),
                ('profilePicture', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'starapp_userprofile',
            },
        ),
        migrations.CreateModel(
            name='VideoTitleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorytitle', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('videomodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='starApp.videosmodel')),
            ],
            options={
                'db_table': 'starapp_videotitlemodel',
            },
        ),
        migrations.CreateModel(
            name='CategoryListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=150)),
                ('videodescription', models.CharField(max_length=1500)),
                ('videothumbnail', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('video', models.URLField(blank=True, max_length=500, null=True)),
                ('video_type', models.CharField(choices=[('standard', 'Standard'), ('youtube', 'YouTube')], default='standard', max_length=10)),
                ('like', models.BooleanField(default=False, help_text='default-0,like-1')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('videotitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='starApp.videotitlemodel')),
            ],
            options={
                'db_table': 'starapp_categorylistmodel',
            },
        ),
        migrations.CreateModel(
            name='UserFavourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='starApp.collectionmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Favourite',
                'verbose_name_plural': 'User Favourites',
                'db_table': 'starapp_userfavourite',
                'unique_together': {('user', 'song')},
            },
        ),
    ]
