# Generated by Django 5.0.6 on 2024-11-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_image', models.ImageField(blank=True, upload_to='uploads')),
                ('alt_text', models.CharField(default='slide_image', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
