# Generated by Django 5.0.6 on 2024-11-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starApp', '0002_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='carousel_image',
            field=models.ImageField(upload_to='uploads'),
        ),
    ]
