# Generated by Django 5.0.6 on 2024-12-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starApp', '0004_otpverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionmodel',
            name='audio',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
