# Generated by Django 5.0.6 on 2025-02-13 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starApp', '0005_alter_collectionmodel_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb_image', models.ImageField(upload_to='uploads')),
                ('thumb_text', models.CharField(default='slide_image', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
