# Generated by Django 5.0.6 on 2025-02-26 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starApp', '0006_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorylistmodel',
            name='video',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
