# Generated by Django 5.0.6 on 2025-03-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starApp', '0007_alter_categorylistmodel_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorylistmodel',
            name='video_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('youtube', 'YouTube')], default='standard', max_length=10),
        ),
    ]
